as_doc/urls.py
from django.urls import path
from . import views

app_name = 'as_doc'
urlpatterns=[
    path("",views.index,name="index"),
    path("login/",views.as_doclogin,name="login"),
    path("register/",views.as_docregister,name="register"),
    path("logout/",views.as_doclogout,name="logout"),
    path("status/",views.status,name="status"),
    path("<str:id>/edit_appointment",views.edit_appointment,name="edit_appointment"),
    path("archive/",views.archive,name="archive"),
    path("<str:id>/edit_archive_appointment",views.edit_archive_appointment,name="edit_archive_appointment"),
]

patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'
urlpatterns=[
    path("",views.index,name="index"),
    path("plogin/",views.patient_login,name="plogin"),
    path("plogout/",views.patient_logout,name="plogout"),
    path("pregister/",views.patient_register,name="pregister"),
    path("forgot-password/",views.forgot_pswd,name="forgotpswd"),
    path("<str:userid>/diseases",views.associateOfDiseases,name="associateOfDiseases"),
]

projectH/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patients/',include("patient.urls")),
    path('assistdoc/',include("as_doc.urls")),
    path('admindoc/',include("admin_doc.urls")),
    path('reception/',include("reception.urls")),
]

patient/models.py
from django.db import models
# from admin_doc.models import User
from django.contrib.auth import get_user_model
User = get_user_model()


GENDER_CHOICES = (
    ('R', 'Resolved'),
    ('NR', 'Not Resolved')
)
# Create your models here.
class diseaseJourney(models.Model):
    users= models.ForeignKey(User,on_delete=models.CASCADE,related_name='diseases')
    disease_name= models.CharField(max_length=100)
    month=models.IntegerField()
    years=models.IntegerField()
    duration = models.DurationField()
    status = models.CharField(max_length=2,choices=GENDER_CHOICES)
    journey_remark = models.TextField()

patient/views.py
#   login handler 
from django.contrib.auth import authenticate, login, logout
#---------------------------------
#       view output
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
#------------------------------
#       Exceptions
from django.db import IntegrityError
#-------------------------------
#       User Model
from django.contrib.auth import get_user_model
User = get_user_model()
#------------------------------
#      Utility Functions
from projectH import utils
#--------------------------------

def index(request):
    if request.user.is_authenticated:
        return render(request,"patient/customer-dashboard.html")
    else:
        return HttpResponseRedirect(reverse("patient:plogin"))

def patient_login(request):
    # already signed-in user cannot go to login page
    if request.user.is_authenticated:
        return render(request,"patient/customer-dashboard.html")

    elif request.method == "POST":
        # Attempt to sign user in
        email = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, email=email, password=password)
        # print(user)
        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('patient:index'))
        else:
            return render(
                request,
                "patient/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "patient/login.html")


def patient_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("patient:index"))

def patient_register(request): 
    if request.method == "POST":
        firstname = request.POST["fname"]
        lastname = request.POST["lname"]
        email = request.POST["email"]
        contact = request.POST["primarycontact"]
        dob = request.POST["dob"]
        gender = request.POST["gender"]
        alternate_contact = request.POST["alternatecontact"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        address=request.POST["address"]
        # new patient type by default
        patient_type = 'N'
        # Ensure password matches confirmation
        if not utils.validate_password(password,confirmation):
            return render(
                request, "patient/register.html", {"message": "Passwords must match."}
            )
        
        # generate user id
        id_list=[]
        while(True):
            user_id =utils.uid_gen()
            id_list = User.objects.filter(user_id=user_id)
            # if user id is unique then take it
            # otherwise generate user id again
            if(len(id_list)==0):
                break
        
        # Attempt to create new user, if user already exists ,raises integrity error
        try:
            print(f"{user_id}\n {firstname}\n {lastname}\n {email}\n {contact}\n {alternate_contact}\n {password} and {confirmation}\n {dob}\n {gender}")
            user = User.objects.create_user(
                firstname=firstname,
                lastname= lastname, 
                email=email,
                password=password,    
                user_id=user_id,      
                primary_contact=contact,
                alternate_contact=alternate_contact,
                gender = gender,
                dob=dob,
                address=address,
                )
            user.patient_type=patient_type
            user.save()
        except IntegrityError:
            return render(
                request,
                "patient/register.html",
                {"message": "Username already taken."},
            )
        login(request, user)
        return HttpResponseRedirect(reverse("patient:index"))
    else:
        return render(request, "patient/register.html")

def forgot_pswd(request):
    return render(
        request,
        "patient/forgot-password.html"
    )

def associateOfDiseases(request,userid):
    user_diseases = User.objects.get(user_id=userid)
    print(user_diseases)
    return render(request,
    "patient/associate-diseases.html")

templates/patient/case-details.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>Customer - Detail Page</title>
		
		<!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="../assets/img/logo.jpeg">
		
		<!-- Bootstrap CSS -->
        <link rel="stylesheet" href="../assets/css/bootstrap.min.css">
		
		<!-- Fontawesome CSS -->
        <link rel="stylesheet" href="../assets/css/font-awesome.min.css">
		
		<!-- Feathericon CSS -->
        <link rel="stylesheet" href="../assets/css/feathericon.min.css">
		
		<!-- Main CSS -->
        <link rel="stylesheet" href="../assets/css/custom.css">

		<style>
			.header {
				background: none;
				border-bottom: none;
				z-index: 1001;
				height: 60px;
				position: static;
				top: 0;
				right: 0;
				/* left: 18%; */
			}

			.sidebar {
				background-color: #fff;
				margin-top: 0;
				-webkit-transition: all 0.2s ease-in-out 0s;
				-ms-transition: all 0.2s ease-in-out 0s;
				transition: all 0.2s ease-in-out 0s;
				width: 240px;
				z-index: 1001;
				position: fixed;
				top: 0px;
				bottom: 0;
				left: 0;
			}

			.sidebar .sidebar-menu > ul > li > a {
				color: #000000;
			}

			.sidebar-menu ul li.active a {
				background-color: #1c3264;
				color: #fff;
			}

			.sidebar-menu > ul > li > a:hover {
				background-color: #1c3264 !important;
				color: #ffffff;
			}

			.user-header {
				background-color: #fff !important;
				display: flex;
				padding: 10px 15px;
				color: black;
			}

			.page-wrapper {
				margin-left: 240px;
				padding-top: 0px;
				position: relative;
				-webkit-transition: all 0.4s ease;
				-ms-transition: all 0.4s ease;
				transition: all 0.4s ease;
			}

			.profile-tab-cont {
				 padding-top: 0; 
			}
			.tab-content {
				 padding-top: 0; 
			}
		</style>
        
    </head>
    <body>
	
		<!-- Main Wrapper -->
        <div class="main-wrapper">
		
			<div class="header">
				
				<div class="header-left"></div>
				<a href="javascript:void(0);" id="toggle_btn">
					<i class="fe fe-text-align-left"></i>
				</a>
				
				<!-- Mobile Menu Toggle -->
				<a class="mobile_btn" id="mobile_btn">
					<i class="fa fa-bars"></i>
				</a>
				<!-- /Mobile Menu Toggle -->				
			</div>
			<!-- /Header -->
		
			
			<!-- Sidebar -->
            <div class="sidebar" id="sidebar">
					
                <div class="sidebar-inner ">
					<div id="sidebar-menu" class="sidebar-menu">
						<ul>
							<li class="menu-title"> 
								<!-- Logo -->
								<div class="m-auto">
									<a href="customer-dashboard.html" class="logo">
										<img src="../assets/img/logo.jpeg" alt="Logo">
									</a>
								</div>
								<!-- /Logo -->
								
							</li>
							<hr>
							<li class="menu-title">
								<div class="user-header">
									<div class="avatar avatar-sm">
										<i class="fe fe-user" style="font-size: 35px"></i>
										<!-- <img src="assets/img/profiles/avatar-01.jpg" alt="User Image" class="avatar-img rounded-circle"> -->
									</div>
									<div class="user-text">
										<h6>Name</h6>
										<p class="text-muted mb-0">name@gmail.com</p>
									</div>
								</div>
							</li>
							<li class="active"> 
								<a href="customer-dashboard.html"><i class="fe fe-home"></i> <span>Dashboard</span></a>
							</li>
							<li> 
								<a href=""><i class="fe fe-user-plus"></i> <span>Profile</span></a>
							</li>
							<li> 
								<a href=""><i class="fe fe-layout"></i> <span>My Case</span></a>
							</li>
							<li>
								<a href="#"><i class="fe fe-logout"></i> <span>Logout</span></a>
							</li>
						</ul>
					</div>
                </div>
            </div>
			<!-- /Sidebar -->
			
			<!-- Page Wrapper -->
            <div class="page-wrapper">
                <div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row">
							<div class="col">
								<h3 class="page-title">Associate Details</h3>
							</div>
						</div>
					</div>
					<!-- /Page Header -->

                    <div class="row">
						<div class="col-12">			
							<div class="tab-content profile-tab-cont">
								<!-- Personal Details Tab -->
								<div class="tab-pane fade show active" id="per_details_tab">
									<!-- Personal Details -->
									<div class="row">
										<div class="col-lg-12">
											<div class="card">
												<div class="card-body">
													
													<div class="row">
														<p class="col-sm-2 text-muted text-sm-end mb-0 mb-sm-3">Case ID</p>
														<p class="col-sm-10">123</p>
													</div>
													<div class="row">
														<p class="col-sm-2 text-muted text-sm-end mb-0 mb-sm-3">Doctor Name</p>
														<p class="col-sm-10">aaa</p>
													</div>
													<div class="row">
														<p class="col-sm-2 text-muted text-sm-end mb-0 mb-sm-3">Chief Complaint</p>
														<p class="col-sm-10">sdd</p>
													</div>
                                                    <div class="row">
														<p class="col-sm-2 text-muted text-sm-end mb-0 mb-sm-3">Last Visit</p>
														<p class="col-sm-10">sdd</p>
													</div>
													<div class="row">
														<p class="col-sm-2 text-muted text-sm-end mb-0 mb-sm-3">Next Visit Date</p>
														<p class="col-sm-10">25 oct</p>
													</div>
													<div class="row">
														<p class="col-sm-2 text-muted text-sm-end mb-0 mb-sm-3">Doctor remark</p>
														<p class="col-sm-10">ddd</p>
													</div>
													<div class="row">
														<p class="col-sm-2 text-muted text-sm-end mb-0">My Feedback</p>
														<!-- <p class="col-sm-10 mb-0">4663  Agriculture Lane</p> -->
                                                        <textarea class="col-sm-10 mb-0" name="" id="" cols="10" rows="10"></textarea>
													</div>
													<button type="button" class="btn btn-primary">Update</button>
												</div>
											</div>
										</div>
									</div>
									<!-- /Personal Details -->

								</div>
								<!-- /Personal Details Tab -->
							</div>
						</div>
					
				
					
				</div>			
			</div>
			<!-- /Page Wrapper -->
		
        </div>
		<!-- /Main Wrapper -->
		
		<!-- jQuery -->
        <script src="../assets/js/jquery-3.6.4.min.js"></script>
		
		<!-- Bootstrap Core JS -->
        <script src="../assets/js/bootstrap.bundle.min.js"></script>
		
		<!-- Slimscroll JS -->
        <script src="../assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>
		
		<!-- Custom JS -->
		<script  src="../assets/js/script.js"></script>
		
    </body>
</html>

templates/patient/index.html
<!-- this is patient dashboard -->
<html>
    <head>
        <title>register</title>
    </head>
    <body>
        <h1>{{user.name}}</h1>
        <h1>This is Patient Module</h1>

        <a href="{% url 'patient:plogout' %}">logout</a>
    </body>
</html>
<!-- Action -->

templates/patient/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>Customer - Login</title>
		
		<!-- Favicon -->
        <!-- <link rel="shortcut icon" type="image/x-icon" href="../../static/assets/img/logo.jpeg"> -->

		<!-- Bootstrap CSS -->
        <!-- <link rel="stylesheet" href="../../static/assets/css/bootstrap.min.css">    -->
		<link rel="stylesheet" href="{% static '/assets/css/bootstrap.min.css' %}"> 
		
		<!-- Fontawesome CSS -->
        <link rel="stylesheet" href="{% static '/assets/css/font-awesome.min.css' %}">
		
		<!-- Main CSS -->

        <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">

		<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

		<style>
			.toggle-password{
				font-size: 16px;
				position: absolute;
				top: 51%;
				right: 23%;
				transform: translateY(-50%);
				-webkit-transform: translateY(-50%);
				-ms-transform: translateY(-50%);
				color: #797979;
				cursor: pointer;
				width: 32px;
				height: 32px;
				border-radius: 50%;
			}
		</style>
        
    </head>
    <body>
	
		<!-- Main Wrapper -->
        <div class="main-wrapper login-body">
            <div class="login-wrapper">
            	<div class="container">
                	<div class="loginbox">
                    	<div class="login-left">
							<img class="img-fluid" src="{% static 'assets/img/logo.jpeg' %}" alt="Logo">
                        </div>
                        <div class="login-right">
							<div class="login-right-wrap">
								<h1>Login</h1>
								<p class="account-subtitle">Access to our dashboard</p>
								<p>
									{% if message %}
										<p>{{message}}</p>
									{% endif %}
								</p>
								<!-- Form -->
								<form action="{% url 'patient:plogin' %}" method="post">
									{% csrf_token %}
									<div class="form-group">
										<input class="form-control" type="text" placeholder="Email" 
										name="email"
										required>
									</div>
									<div class="form-group">
										<div class="pass-group">
											<input class="form-control pass-input" type="password" placeholder="Password" 
											name="password"
											required>
											<!-- <span class="feather-eye toggle-password"></span> -->
											<i class="fa fa-eye feather-eye toggle-password " aria-hidden="true"></i>
										</div>
									</div>
									<div class="form-group">
										<button class="btn btn-primary w-100 " type="submit">Login</button>
									</div>
								</form>
								<!-- /Form -->
								
								<div class="text-center forgotpass"><a href="{% url 'patient:forgotpswd' %}">Forgot Password?</a></div>
																
								<div class="text-center dont-have">Don’t have an account? <a href="{% url 'patient:pregister' %}">Register</a></div>
							</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
		<!-- /Main Wrapper -->
		
		<!-- jQuery -->
        <script src="{% static 'assets/js/jquery-3.6.4.min.js' %}"></script>
		
		<!-- Bootstrap Core JS -->
        <script src="{% static  'assets/js/bootstrap.bundle.min.js' %}"></script>
		
		<!-- Custom JS -->
		<script src="{% static 'assets/js/script.js' %}"></script>
		<script>
				if ($('.toggle-password').length > 0) {
				$(document).on('click', '.toggle-password', function () {
					$(this).toggleClass("feather-eye-off");
					var input = $(".pass-input");
					if (input.attr("type") == "password") {
						input.attr("type", "text");
					} else {
						input.attr("type", "password");
					}
				});
			}
		</script>
		
    </body>
</html>

templates/patient/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
	<title>Customer Register</title>

	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="{% static '/assets/img/favicon.png' %}">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static '/assets/css/bootstrap.min.css' %}">

	<!-- Fontawesome CSS -->
	<link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">

	<!-- Main CSS -->
	<link rel="stylesheet" href="{% static '/assets/css/custom.css' %}">

	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
		integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

	<style>
		.toggle-password {
			font-size: 16px;
			/* position: absolute; */
			position: fixed;
			top: 54%;
			right: 23%;
			transform: translateY(-50%);
			-webkit-transform: translateY(-50%);
			-ms-transform: translateY(-50%);
			color: #797979;
			cursor: pointer;
			width: 32px;
			height: 32px;
			border-radius: 50%;
		}

		.toggle-passwords {
			font-size: 16px;
			position: fixed;
			top: 64%;
			right: 23%;
			transform: translateY(-50%);
			-webkit-transform: translateY(-50%);
			-ms-transform: translateY(-50%);
			color: #797979;
			cursor: pointer;
			width: 32px;
			height: 32px;
			border-radius: 50%;
		}
	</style>

</head>

<body>

	<!-- Main Wrapper -->
	<div class="main-wrapper login-body">
		<div class="login-wrapper">
			<div class="container">
				<div class="loginbox">
					<div class="login-left">
						<img class="img-fluid" src="../../static/assets/img/logo-white.png" alt="Logo">
					</div>
					<div class="login-right">
						<div class="login-right-wrap">
							<h1>Register</h1>
							<p class="account-subtitle">Access to our dashboard</p>

							<!-- Form -->
							<form action="{% url 'patient:pregister' %}" name="myForm" id="registrationForm"
								onsubmit="return validateForm()" method="post">
								{% csrf_token %}
								<!-- <form action="login.html" name="myForm" id="registrationForm" onsubmit="return validateForm()"> -->
								<!-- name -->
								<div class="row">
									<div class="col-sm-6">
										<div class="form-group" id="iname">
											<input class="form-control" type="text" id="name" name="fname" required
												placeholder="first name">
											<span class="spin"></span>
										</div>
									</div>
									<div class="col-sm-6">
										<div class="form-group" id="iname">
											<input class="form-control" type="text" id="name" name="lname" required
												placeholder="last name">
											<span class="spin"></span>
										</div>
									</div>
									<!-- email -->
									<div class="form-group" id="iemail">
										<input class="form-control" type="email" id="email" name="email" required
											placeholder="Email">
										<span class="spin"></span>
									</div>
									<!--contact  -->
									<div class="form-group" id="iemail">
										<input class="form-control" type="number" id="email" name="primarycontact" required
											placeholder="Contact">
										<span class="spin"></span>
									</div>
									<!-- aternate  contact-->
									<div class="form-group" id="iemail">
										<input class="form-control" type="number" id="email" name="alternatecontact"
											placeholder="alternate contact">
										<span class="spin"></span>
									</div>
									<!-- dob -->
									<div class="form-group" id="iemail">
										<input class="form-control" type="date" id="email" name="dob" required
											placeholder="Date of Birth">
										<span class="spin"></span>
									</div>
									<!-- gender -->
									<div class="form-group" id="iemail">
										<select class="form-select" aria-label="Default select example" name="gender">
											<option value="M">Male</option>
											<option value="F">Female</option>
											<option value="O">Other</option>
										</select>
									</div>
									<!-- pswd -->
									<div class="form-group" id="ipass">
										<div class="input-group" id="show_hide_password_">
											<input class="form-control" type="password" name="password" placeholder="password">
											<div class="input-group-addon">
												<a href=""><i class="fa fa-eye-slash" aria-hidden="true"></i></a>
											</div>
										</div>
									</div>
									<div class="form-group" id="cpass">
										<div class="input-group" id="show_hide_password">
											<input class="form-control" type="password" name="confirmation" placeholder="confirm password">
											<div class="input-group-addon">
											  <a href=""><i class="fa fa-eye-slash" aria-hidden="true"></i></a>
											</div>
										  </div>
									</div>
									<div class="input-group" id="show_hide_password">
										<input class="form-control" type="text" name="address" placeholder="Address">
										</div>
									  </div>
								</div>
								</div>								
								<div class="form-group mb-0">
									<button class="btn btn-primary w-100" type="submit">Register</button>
								</div>
							</form>
							<!-- /Form -->

							<div class="text-center dont-have">Already have an account? <a
									href="{% url 'patient:pregister' %}">Login</a></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- /Main Wrapper -->

	<!-- jQuery -->
	<script src="../../static/assets/js/jquery-3.6.4.min.js"></script>

	<!-- Bootstrap Core JS -->
	<script src="../../static/assets/js/bootstrap.bundle.min.js"></script>

	<!-- Custom JS -->
	<script src="../../static/assets/js/script.js"></script>

	<!-- <script>
			function validateForm() {
				// Get form input values
				var name = document.getElementById("name").value;
				var email = document.getElementById("email").value;
				var password = document.getElementById("password").value;
	
				// Regular expression to validate email format
				var emailRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
	
				// Check if name is empty
				if (name.trim() === "") {
					alert("Name field is required");
					return false;
				}
	
				// Check if email is empty and matches the email format
				if (email.trim() === "") {
					alert("Email field is required");
					return false;
				} else if (!email.match(emailRegex)) {
					alert("Invalid email format");
					return false;
				}
	
				// Check if password is empty and meets the minimum length
				if (password.trim() === "") {
					alert("Password field is required");
					return false;
				} else if (password.length < 6) {
					alert("Password must be at least 6 characters long");
					return false;
				}
	
				// If all checks pass, the form is valid and can be submitted
				return true;
			}
		</script> -->


	<script>
		$(document).ready(function () {
			$("#show_hide_password a").on('click', function (event) {
				event.preventDefault();
				if ($('#show_hide_password input').attr("type") == "text") {
					$('#show_hide_password input').attr('type', 'password');
					$('#show_hide_password i').addClass("fa-eye-slash");
					$('#show_hide_password i').removeClass("fa-eye");
				} else if ($('#show_hide_password input').attr("type") == "password") {
					$('#show_hide_password input').attr('type', 'text');
					$('#show_hide_password i').removeClass("fa-eye-slash");
					$('#show_hide_password i').addClass("fa-eye");
				}
			});
		});
		$(document).ready(function () {
			$("#show_hide_password_ a").on('click', function (event) {
				event.preventDefault();
				if ($('#show_hide_password_ input').attr("type") == "text") {
					$('#show_hide_password_ input').attr('type', 'password');
					$('#show_hide_password_ i').addClass("fa-eye-slash");
					$('#show_hide_password_ i').removeClass("fa-eye");
				} else if ($('#show_hide_password_ input').attr("type") == "password") {
					$('#show_hide_password_ input').attr('type', 'text');
					$('#show_hide_password_ i').removeClass("fa-eye-slash");
					$('#show_hide_password_ i').addClass("fa-eye");
				}
			});
		});
		// 	if ($('.toggle-password').length > 0) {
		// 	$(document).on('click', '.toggle-password', function () {
		// 		$(this).toggleClass("feather-eye-off");
		// 		var input = $(".pass-input");
		// 		if (input.attr("type") == "password") {
		// 			input.attr("type", "text");
		// 		} else {
		// 			input.attr("type", "password");
		// 		}
		// 	});
		// }

		// if ($('.toggle-passwords').length > 0) {
		// 	$(document).on('click', '.toggle-passwords', function () {
		// 		$(this).toggleClass("feather-eye-off");
		// 		var input = $(".pass-input-sub");
		// 		if (input.attr("type") == "password") {
		// 			input.attr("type", "text");
		// 		} else {
		// 			input.attr("type", "password");
		// 		}
		// 	});
		// }
	</script>

	<!-- form validation by supriya -->
	<script>

		function clearErrors() {
			errors = document.getElementsByClassName("spin");
			for (let item of errors) {
				item.innerHTML = "";
			}
		}

		function seterror(id, error) {
			element = document.getElementById(id);
			element.getElementsByClassName('spin')[0].innerHTML = error;
		}

		function validateForm() {
			var returnval = true;
			clearErrors();

			var name = document.forms['myForm']["name"].value;
			if (name.length < 5) {
				seterror("iname", "length of name is too short");
				returnval = false;
			}

			if (name.length == 0) {
				seterror("iname", "name cannot be empty");
				returnval = false;
			}

			var password = document.forms['myForm']["password"].value;
			var capitalLetter = /[A-Z]/;
			var lowercaseLetter = /[a-z]/;
			var numbers = /[0-9]/;
			var specialSymbol = /[!@#$%^&*()_+{}:;<>,.?~\/-=|]/;

			if (
				capitalLetter.test(password) &&
				lowercaseLetter.test(password) &&
				(password.match(numbers) && password.match(numbers).length >= 3) &&
				specialSymbol.test(password) &&
				password.length >= 8
			) {
				// Password meets the criteria
				// clearError("ipass"); // This function should clear the error message]]
			} else {
				var errorMessage = "Password should have at least one capital letter, one lowercase letter, at least three numbers, one special symbol, and a minimum length of 8 characters.";
				var errorStyle = {
					padding: "13px", // Adjust the padding value as needed
					color: "red",   // Adjust other styles as needed
					// Add more styles here if desired
				};
				seterror("ipass", errorMessage, errorStyle);
				returnval = false;
			}

			function clearError(fieldId) {
				// This function clears the error message by setting its innerHTML to an empty string
				document.getElementById(fieldId).innerHTML = "";
			}


			var cpassword = document.forms['myForm']["cpassword"].value;
			if (cpassword != password) {
				seterror("cpass", "password and confirm password should match!");
				returnval = false;

				var cpass = document.getElementById("cpass");
				if (cpass) {
					cpass.style.marginTop = ""; // Adjust the margin value as needed
				}
			}

			return returnval;
		}
	</script>
</body>

</html>