as_doc/urls.py
from django.urls import path
from . import views

app_name = 'as_doc'
urlpatterns=[
    path("",views.index,name="index"),
    path("login/",views.as_doclogin,name="login"),
    path("register/",views.as_docregister,name="register"),
    path("logout/",views.as_doclogout,name="logout"),
    path("status/",views.status,name="status"),
    path("<str:id>/edit_appointment",views.edit_appointment,name="edit_appointment"),
    path("archive/",views.archive,name="archive"),
    path("<str:id>/edit_archive_appointment",views.edit_archive_appointment,name="edit_archive_appointment"),
]

patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'
urlpatterns=[
    path("",views.index,name="index"),
    path("plogin/",views.patient_login,name="plogin"),
    path("plogout/",views.patient_logout,name="plogout"),
    path("pregister/",views.patient_register,name="pregister"),
    path("forgot-password/",views.forgot_pswd,name="forgotpswd"),
    path("<str:userid>/diseases",views.associateOfDiseases,name="associateOfDiseases"),
]

projectH/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patients/',include("patient.urls")),
    path('assistdoc/',include("as_doc.urls")),
    path('admindoc/',include("admin_doc.urls")),
    path('reception/',include("reception.urls")),
]

reception/urls.py
from django.urls import path
from . import views

app_name = 'reception'
urlpatterns=[

    path("",views.index,name='index'),
    path("login/",views.reception_login,name="login"),
    path("logout/",views.reception_logout,name="logout"),
#   doctors
    path("doctors/",views.show_doctors,name="show_doctors"),
    path("add-doctor/",views.add_doctor,name="add_doctor"),
    path("<str:id>/edit-doctor/",views.edit_doctor,name="edit_doctor"),
    path("<str:id>/delete-doctor/",views.delete_doctor,name="delete_doctor"),
    path("<str:id>/update-doctor-password/",views.update_doctor_password,name="update_doctor_password"),
#   patients
    path("patients/",views.show_patients,name="show_patients"),
    path("add-patient/",views.add_patient,name="add_patient"),
    path("<str:id>/edit-patient/",views.edit_patient,name="edit_patient"),
    path("<str:id>/delete-patient/",views.delete_patient,name="delete_patient"),
    path("<str:id>/update-patient-password/",views.update_patient_password,name="update_patient_password"),

    # appointments
    path("appointments/",views.show_appointments,name="show_appointments"),
    path("add-appointment/",views.add_appointment,name="add_appointment"),
    path("<str:appointment_id>/edit-appointment/",views.edit_appointment,name="edit_appointment"),
    path("<str:appointment_id>/delete-appointment/",views.delete_appointment,name="delete_appointment"),

    # archives
    path("archive-appointment/",views.show_archive_appointments,name="show_archive_appointments"),
    path("<str:appointment_id>/archive_appointment/",views.archive_appointment,name="archive_appointment"),
    path("<str:appointment_id>/unarchive_appointment/",views.unarchive_appointment,name="unarchive_appointment"),
    path("<str:appointment_id>/edit_unarchive_appointment/",views.edit_archive_appointment,name="edit_archive_appointment"),


    # Doctor Schedule
    path("schedules/",views.show_doctor_schedules,name="show_doctor_schedules"),
    path("add-schedule/",views.add_doctor_schedule,name="add_doctor_schedule"),
    path("<int:id>/edit-schedule/",views.edit_doctor_schedule,name="edit_doctor_schedule"),
    path("<int:id>/delete-schedule/",views.delete_doctor_schedule,name="delete_doctor_schedule"),


    
]

patient/views.py
#   login handler 
from django.contrib.auth import authenticate, login, logout
#---------------------------------
#       view output
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
#------------------------------
#       Exceptions
from django.db import IntegrityError
#-------------------------------
#       User Model
from django.contrib.auth import get_user_model
User = get_user_model()
#------------------------------
#      Utility Functions
from projectH import utils
#--------------------------------

def index(request):
    if request.user.is_authenticated:
        return render(request,"patient/customer-dashboard.html")
    else:
        return HttpResponseRedirect(reverse("patient:plogin"))

def patient_login(request):
    # already signed-in user cannot go to login page
    if request.user.is_authenticated:
        return render(request,"patient/customer-dashboard.html")

    elif request.method == "POST":
        # Attempt to sign user in
        email = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, email=email, password=password)
        # print(user)
        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('patient:index'))
        else:
            return render(
                request,
                "patient/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "patient/login.html")


def patient_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("patient:index"))

def patient_register(request): 
    if request.method == "POST":
        firstname = request.POST["fname"]
        lastname = request.POST["lname"]
        email = request.POST["email"]
        contact = request.POST["primarycontact"]
        dob = request.POST["dob"]
        gender = request.POST["gender"]
        alternate_contact = request.POST["alternatecontact"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        address=request.POST["address"]
        # new patient type by default
        patient_type = 'N'
        # Ensure password matches confirmation
        if not utils.validate_password(password,confirmation):
            return render(
                request, "patient/register.html", {"message": "Passwords must match."}
            )
        
        # generate user id
        id_list=[]
        while(True):
            user_id =utils.uid_gen()
            id_list = User.objects.filter(user_id=user_id)
            # if user id is unique then take it
            # otherwise generate user id again
            if(len(id_list)==0):
                break
        
        # Attempt to create new user, if user already exists ,raises integrity error
        try:
            print(f"{user_id}\n {firstname}\n {lastname}\n {email}\n {contact}\n {alternate_contact}\n {password} and {confirmation}\n {dob}\n {gender}")
            user = User.objects.create_user(
                firstname=firstname,
                lastname= lastname, 
                email=email,
                password=password,    
                user_id=user_id,      
                primary_contact=contact,
                alternate_contact=alternate_contact,
                gender = gender,
                dob=dob,
                address=address,
                )
            user.patient_type=patient_type
            user.save()
        except IntegrityError:
            return render(
                request,
                "patient/register.html",
                {"message": "Username already taken."},
            )
        login(request, user)
        return HttpResponseRedirect(reverse("patient:index"))
    else:
        return render(request, "patient/register.html")

def forgot_pswd(request):
    return render(
        request,
        "patient/forgot-password.html"
    )

def associateOfDiseases(request,userid):
    user_diseases = User.objects.get(user_id=userid)
    print(user_diseases)
    return render(request,
    "patient/associate-diseases.html")

reception/views.py
#   login handler 
from django.contrib.auth import authenticate, login, logout
#---------------------------------
#       view output
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
#--------------------------------------------------------
#      views constraint
from django.contrib.auth.decorators import login_required
#--------------------------------------------------------
#       Exceptions
from django.db import IntegrityError
#------------------------------
#      Utility Functions
from projectH import utils
#-------------------------------
#		  DB Models
#-----------------------------
#       User Model
from django.contrib.auth import get_user_model
User = get_user_model()
#-------------------------------
#       Schedule Model
from reception.models import Schedule,DaysOfTheWeek
#--------------------------------------
#		Appointment Model
from reception.models import Appointment
#--------------------------------------
#--------------------------------


def index(request):
	if request.user.is_authenticated and request.user.groups.filter(name="Receptionist").exists():
		return render(request,"reception/dashboard.html",{
			"doctor_list":User.objects.filter(is_as_doc=True),
			"patient_list":User.objects.filter(is_as_doc=False,is_admin_doc=False),
			"new_patient_count":len(User.objects.filter(is_as_doc=False,is_admin_doc=False,patient_type='N')),
			"existing_patient_count":len(User.objects.filter(is_as_doc=False,is_admin_doc=False,patient_type='E'))
		})
	else:
		if request.user.is_authenticated:
			logout(request)
		return render(request,"reception/index.html") 
		

def reception_login(request):
	if request.user.is_authenticated and user.groups.filter(name="Receptionist").exists():
		return render(request,"reception/dashboard.html")
	elif request.method == "GET":
		return HttpResponseRedirect(reverse("reception:index"))

	elif request.method == "POST":
		email = request.POST["email"]
		password = request.POST["pwd"]
		# users = User.objects.filter(is_admin_doc=True)

		users= User.objects.filter(email=email,is_admin_doc=True)
		if not users.exists():
			return render(request,"reception/index.html",
			{"message": "Invalid username and/or password."},)
		user = authenticate(email=email,password=password)

		if user.is_admin_doc and user.groups.filter(name="Receptionist").exists():
			login(request,user)
			return HttpResponseRedirect(reverse("reception:index"))
		return render(request,"reception/index.html",
			{"message": user.email + " does not have access, contact your admin."},)


def reception_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse("reception:index"))

# doctors
@login_required(login_url="login")
def show_doctors(request):
	#  get list of all doctors
	doctors = User.objects.filter(is_as_doc=True)
	if request.method=='GET':
		return render(request,"reception/doctors.html",
		{
			"doctors":doctors,
		})
	elif request.method=='POST':
		search_input = request.POST["searched_input"]
		search_input = search_input.upper()
		requested_doctor=[]
		for doctor in doctors:
			if (search_input in (doctor.firstname).upper()) or (search_input in (doctor.lastname).upper()):
				requested_doctor.append(doctor)
				print("found",doctor)
		return render(request,"reception/doctors.html",
		{
			"doctors":requested_doctor,
		})

@login_required(login_url="login")
def add_doctor(request):
	if request.method=='POST':
		firstname = request.POST["first_name"]
		lastname = request.POST["last_name"]
		email = request.POST["emailid"]
		dob = request.POST["dob"]
		emp_id = request.POST["employee_id"]
		gender = request.POST["gender"]
		contact = request.POST["phone"]
		alternate_contact = request.POST["alphone"]
		password = request.POST["password"]
		confirmation = request.POST["password"]
		status = request.POST["status"]
		address = ""

		# convert string to date format
		dob = utils.str_to_date(dob)

		# print(f"{firstname}\n {email}\n {contact}\n {alternate_contact}\n {password} and {confirmation}\n {dob}\n {gender}\n {status}\n")
		# return HttpResponse("Success")
		# Attempt to create new user, if user already exists ,raises integrity error
		try:
			user = User.objects.create_as_doc(
            firstname=firstname,
            lastname= lastname, 
            email=email,
            password=password,          
            primary_contact=contact,
            user_id=emp_id,
            alternate_contact=alternate_contact,
            gender = gender,
            dob=dob,
			address=address,
            )
			user.status = status
			user.save()
		except IntegrityError:
			return render(
                request,
                "reception/add-doctor.html",
                {"error": "Email already taken.",
				"emp_id":emp_id,},
            )
		id_list=[]
		while(True):
			emp_id =utils.empid_gen()
			id_list = User.objects.filter(user_id=emp_id)
			# if user id is unique then take it
			# otherwise generate user id again
			if(len(id_list)==0):
			    break
		return render(request,
			"reception/add-doctor.html",
			{"success":"Doctor added successfully",
			"emp_id":emp_id},)
	else:       
		# generate user id
		id_list=[]
		while(True):
			emp_id =utils.empid_gen()
			id_list = User.objects.filter(user_id=emp_id)
			# if user id is unique then take it
			# otherwise generate user id again
			if(len(id_list)==0):
			    break
		return render(request,"reception/add-doctor.html",
		{
			"emp_id":emp_id,
		},)

@login_required(login_url="login")
def edit_doctor(request,id):
	user = User.objects.get(user_id=id)
	if request.method=='GET':
		return render(request,
		"reception/edit-doctor.html",
		{
			"doctor":user,
			"dob":utils.date_to_string(user.dob),
		})
	elif request.method=='POST':
		firstname = request.POST["first_name"]
		lastname = request.POST["last_name"]
		email = request.POST["emailid"]
		dob = request.POST["dob"]
		contact = request.POST["phone"]
		alternate_contact = request.POST["alphone"]
		status = request.POST["status"]
		
		if (len(User.objects.filter(email=email))!=0) and (email != user.email):
			return render(request,
		"reception/edit-doctor.html",
		{
			"doctor":user,
			"dob":utils.date_to_string(user.dob),
			"error":"Email is taken by someone, Please give another mail."
		})

		# convert string to date format
		dob = utils.str_to_date(dob)

		user.firstname = firstname
		user.lastname = lastname
		user.email = email
		user.dob = dob
		user.primary_contact=contact
		user.alternate_contact=alternate_contact
		user.status = status
		user.save()
		return HttpResponseRedirect(reverse("reception:show_doctors"))

@login_required(login_url="login")
def delete_doctor(request,id):
	user = User.objects.get(user_id=id)
	user.delete()
	return HttpResponseRedirect(reverse("reception:show_doctors"))

@login_required(login_url="login")
def update_doctor_password(request,id):
	user = User.objects.get(user_id=id)
	if request.method=='GET':
		return render(request,
		"reception/update-password.html",
		{
			"email":user.email,
			"id":user.user_id,
		}
		)
	elif request.method=='POST':
		password = request.POST["pwd"]
		confirm_password = request.POST["cpwd"]
		
        # Ensure password matches confirm_password
		if not utils.validate_password(password,confirm_password):
			return render(request,
			"reception/update-password.html",
			{
				"email":user.email,
				"id":user.user_id,
				"message": "Passwords must match.",
			}
			)
		# if passwords are matched
		user.set_password(password)
		user.save()
		return HttpResponseRedirect(reverse("reception:show_doctors"))

# Patients
@login_required(login_url="login")
def show_patients(request):
	all_patient = User.objects.filter(is_as_doc=False,is_admin_doc=False)
	current_year = utils.get_year()
	
	if request.method  == 'GET':
		return render(request,
		"reception/patients.html",{
			# get all the list of patients
			"patients":all_patient,
			"current_year":current_year,
		})
	elif request.method  == 'POST':
		search_patient_input = request.POST["searched_patient"].upper()
		requested_patient=[]
		for patient in all_patient:
			# searched by name, id, phone number
			if (search_patient_input in (patient.firstname).upper()) or (search_patient_input in (patient.lastname).upper()) or (search_patient_input in (patient.user_id).upper()) or (search_patient_input in patient.primary_contact) or (search_patient_input in patient.alternate_contact):
				print("found ",patient)
				requested_patient.append(patient)
		return render(request,
		"reception/patients.html",{
			# get all the list of patients
			"patients":requested_patient,
			"current_year":current_year,
		}) 



@login_required(login_url="login")
def add_patient(request):
	if request.method == 'POST':
		firstname = request.POST["first_name"]
		lastname = request.POST["last_name"]
		email = request.POST["emailid"]
		dob = request.POST["dob"]
		gender = request.POST["gender"]
		contact = request.POST["phone"]
		alternate_contact = request.POST["aphone"]
		password = request.POST["password"]
		confirmation = request.POST["password"]
		patient_type = request.POST["patient_type"]
		address = request.POST["address"]

		dob = utils.str_to_date(dob)
		# generate user id
		id_list=[]
		while(True):
			user_id =utils.uid_gen()
			id_list = User.objects.filter(user_id=user_id)
			# if user id is unique then take it
			# otherwise generate user id again
			if(len(id_list)==0):
			    break
		        # Attempt to create new user, if user already exists ,raises integrity error
		# print(f"{user_id}\n {firstname}\n {lastname}\n {email}\n {contact}\n {alternate_contact}\n {password} and {confirmation}\n {dob}\n {gender}\n {patient_type}")
		try:
			user = User.objects.create_user(
                firstname=firstname,
                lastname= lastname, 
                email=email,
                password=password,    
                user_id=user_id,      
                primary_contact=contact,

templates/reception/appointments.html
{% extends 'reception_base.html' %}
{% load static %}
{% load mathfilters %}

{% block content %}
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-sm-4 col-3">
                <h4 class="page-title">Appointments</h4>
            </div>
            <div class="col-sm-8 col-9 text-right m-b-20">
                <a href="{% url 'reception:add_appointment' %}" class="btn btn-primary btn-rounded float-right"><i
                        class="fa fa-plus"></i> Add Appointment</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 col-6">
                <form class="form-inline" method="post" action="{% url 'reception:show_appointments' %}">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="search" placeholder="ID or Patient name" name="searched_appointment" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
            </div>
        </div>
        <div class="table-responsive">
            <table class="datatable table table-stripped ">
                <thead>
                    <tr>
                        <th>Appointment ID</th>
                        <th>Patient Name</th>
                        <th>Age</th>
                        <th>Doctor Name</th>
                        <th>Appointment Date</th>
                        <th>Appointment Time</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- for loop starts -->
                    {% for appointment in appointments %}
                    <tr>
                        <td>APT-{{appointment.appointment_id}}</td>
                        <td>{{appointment.patient.firstname}} {{appointment.patient.lastname}}</td>
                        <td>{{current_year|sub:appointment.patient.dob.year}}</td>
                        <td>{{appointment.doctor.firstname}} {{appointment.doctor.lastname}}</td>
                        <td>{{appointment.date}}</td>
                        <td>{{appointment.time}}</td>
                        {% if appointment.status == 'C' %}
                        <td><span class="custom-badge status-orange">Confirmed</span></td>
                        {% elif appointment.status == 'A' %}
                        <td><span class="custom-badge status-green">Active</span></td>
                        {% endif %}
                        <td class="text-right">
                            <div class="dropdown dropdown-action">
                                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown"
                                    aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item"
                                        href="{% url 'reception:edit_appointment' appointment.appointment_id %}"><i
                                            class="fa fa-pencil m-r-5"></i> Edit</a>
                                    <a class="dropdown-item"
                                        href="{% url 'reception:archive_appointment' appointment.appointment_id %}"
                                        onclick="return confirmArchive()"><i class="fa fa-archive m-r-5"></i> Archive</a>
                                    <a class="dropdown-item"
                                        href="{% url 'reception:delete_appointment' appointment.appointment_id %}"
                                        onclick="return confirmDelete()"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <!-- for loop ends -->
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

</div>

<script language="JavaScript" type="text/javascript">
    function confirmDelete() {
        return confirm('Are you sure want to delete this Appointment?');
    }
    function confirmArchive() {
        return confirm('Are you sure want to move this appointment to archive ?');
    }
</script>
{% endblock %}

templates/reception/archive-appointments.html
{% extends 'reception_base.html' %}
{% load static %}
{% load mathfilters %}

{% block content %}
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-sm-4 col-3">
                <h4 class="page-title">Archive Appointments</h4>
            </div>
            <div class="col-sm-8 col-9 text-right m-b-20">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 col-6">
                <form class="form-inline" method="post" action="{% url 'reception:show_archive_appointments' %}">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="search" placeholder="ID or Patient name" name="searched_archived_appointment" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
            </div>
        </div>
        <div class="table-responsive">
            <table class="datatable table table-stripped ">
                <thead>
                    <tr>
                        <th>Appointment ID</th>
                        <th>Patient Name</th>
                        <th>Age</th>
                        <th>Doctor Name</th>
                        <th>Appointment Date</th>
                        <th>Appointment Time</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- for loop starts -->
                    {% for appointment in appointments %}
                    <tr>
                        <td>APT-{{appointment.appointment_id}}</td>
                        <td>{{appointment.patient.firstname}} {{appointment.patient.lastname}}</td>
                        <td>{{current_year|sub:appointment.patient.dob.year}}</td>
                        <td>{{appointment.doctor.firstname}} {{appointment.doctor.lastname}}</td>
                        <td>{{appointment.date}}</td>
                        <td>{{appointment.time}}</td>
                        {% if appointment.status == 'D' %}
                        <td><span class="custom-badge status-grey">Done</span></td>
                        {% endif %}
                        <td class="text-right">
                            <div class="dropdown dropdown-action">
                                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown"
                                    aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item"
                                        href="{% url 'reception:unarchive_appointment' appointment.appointment_id %}"><i
                                            class="fa fa-archive m-r-5"></i> Unarchive</a>
                                    <a class="dropdown-item"
                                        href="{% url 'reception:edit_archive_appointment' appointment.appointment_id %}"><i
                                            class="fa fa-pencil m-r-5"></i> Edit Archive</a>
                                    <a class="dropdown-item"
                                        href="{% url 'reception:delete_appointment' appointment.appointment_id %}"
                                        onclick="return confirmDelete()"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <!-- for loop ends -->
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

</div>

<script language="JavaScript" type="text/javascript">
    function confirmDelete() {
        return confirm('Are you sure want to delete this Appointment?');
    }
</script>
{% endblock %}

templates/reception/patients.html
{% extends 'reception_base.html' %}
{% load static %}
{% load mathfilters %}

{% block content %}
<style>
    .btn-primary {
        border-color: transparent;
        background-color: #3a3a3a;
    }

    .btn-primary:hover {
        border: 1px solid #3a3a3a;
        background-color: #fff;
        color:#000;
    }

    .btn-primary:active:not(:disabled):not(.disabled)
    {
        border: 1px solid #3a3a3a;
        background-color: #fff;
        color:#000;
    }

    .page-item.active .page-link {
        background-color: #3a3a3a;
        border-color: #3a3a3a;
    }
</style>
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-sm-4 col-3">
                <h4 class="page-title">Patients</h4>
            </div>
            <div class="col-sm-8 col-9 text-right m-b-20">
                <a href="{% url 'reception:add_patient' %}" class="btn btn-primary btn-rounded float-right"><i
                        class="fa fa-plus"></i> Add Patient</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 col-6">
                <form class="form-inline" method="post" action="{% url 'reception:show_patients' %}">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="search" placeholder="Patient Name / ID /Ph.no" name="searched_patient" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
            </div>
        </div>
        <div class="table-responsive overflow-hidden">
            <table class="datatable table table-stripped ">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- for loop start -->
                    {% for patient in patients %}
                    <tr>
                        <td>{{patient.firstname}} {{patient.lastname}}</td>
                        <td>{{ current_year |sub:patient.dob.year }}</td>
                        <td>{{patient.email}}</td>
                        <td>{{patient.primary_contact}}</td>
                        {% if patient.patient_type == 'N' %}
                        <td><span class="custom-badge status-green">New Patient</span></td>
                        {% else %}
                        <td><span class="custom-badge status-blue">Existing Patient</span></td>
                        {% endif %}
                        <td class="text-right">
                            <div class="dropdown dropdown-action">
                                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown"
                                    aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item"
                                        href="{% url 'reception:edit_patient' patient.user_id %}"><i
                                            class="fa fa-pencil m-r-5"></i> Edit</a>
                                    <a class="dropdown-item"
                                        href="{% url 'reception:delete_patient' patient.user_id %}" onclick="return confirmDelete()"><i  class="fa fa-trash-o m-r-5" ></i> Delete</a>
                                    <a class="dropdown-item"
                                        href="{% url 'reception:update_patient_password' patient.user_id %}"><i
                                            class="fa fa-eye m-r-5"></i> Change Password</a>
                                </div>
                        </td>
                        {% endfor %}
                        <!-- for loop end -->
                    </tr>
                </tbody>
            </table>
        </div>

    </div>

</div>


<script language="JavaScript" type="text/javascript">
    function confirmDelete() {
        return confirm('Are you sure want to delete this Patient?');
    }
</script>
{% endblock %}