as_doc/urls.py
from django.urls import path
from . import views

app_name = 'as_doc'
urlpatterns=[
    path("",views.index,name="index"),
    path("login/",views.as_doclogin,name="login"),
    path("register/",views.as_docregister,name="register"),
    path("logout/",views.as_doclogout,name="logout"),
    path("status/",views.status,name="status"),
    path("<str:id>/edit_appointment",views.edit_appointment,name="edit_appointment"),
    path("archive/",views.archive,name="archive"),
    path("<str:id>/edit_archive_appointment",views.edit_archive_appointment,name="edit_archive_appointment"),
]

patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'
urlpatterns=[
    path("",views.index,name="index"),
    path("plogin/",views.patient_login,name="plogin"),
    path("plogout/",views.patient_logout,name="plogout"),
    path("pregister/",views.patient_register,name="pregister"),
    path("forgot-password/",views.forgot_pswd,name="forgotpswd"),
    path("<str:userid>/diseases",views.associateOfDiseases,name="associateOfDiseases"),
]

projectH/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patients/',include("patient.urls")),
    path('assistdoc/',include("as_doc.urls")),
    path('admindoc/',include("admin_doc.urls")),
    path('reception/',include("reception.urls")),
]

as_doc/models.py
from django.db import models

# Create your models here.

as_doc/views.py
#   login handler 
from django.contrib.auth import authenticate, login, logout
#---------------------------------
#       view output
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
#--------------------------------------------------------
#      views constraint
from django.contrib.auth.decorators import login_required
#--------------------------------------------------------
#       Exceptions
from django.db import IntegrityError
#-------------------------------
#       User Model
from django.contrib.auth import get_user_model
User = get_user_model()
#------------------------------
# Appointment Model
from reception.models import Appointment
#-------------------------------
#      Utility Functions
from projectH import utils
#--------------------------------

def index(request):
    if request.user.is_authenticated:
        user = User.objects.get(user_id=request.user.user_id)
        doctor_appointments = user.assigned_patients.all().exclude(status='D')
        # print(user.firstname,user.lastname)
        # active appointment will show first
        # doctor_appointments.sort(key=lambda x: x.status, reverse=True)
        doctor_appointments = sorted(doctor_appointments, key=lambda x: x.date,reverse=True)
        return render(request,"as_doc/appointment.html",
        {
            "doctor":user,
            "appointments":doctor_appointments,
            "current_year":utils.get_year(),
        })
    else:
        return HttpResponseRedirect(reverse("as_doc:login"))

def as_doclogin(request):
    if request.method == "POST":
        # Attempt to sign user in
        email = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, email=email, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('as_doc:index'))
        else:
            return render(
                request,
                "as_doc/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "as_doc/login.html")

def as_doclogout(request):
    logout(request)
    return HttpResponseRedirect(reverse("as_doc:index"))

def as_docregister(request):
    if request.method == "POST":
        firstname = request.POST["fname"]
        lastname = request.POST["lname"]
        email = request.POST["email"]
        contact = request.POST["primarycontact"]
        dob = request.POST["dob"]
        gender = request.POST["gender"]
        alternate_contact = request.POST["alternatecontact"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        address=""

        # Ensure password matches confirmation
        if not utils.validate_password(password,confirmation):
            return render(
                request, "as_doc/register.html", {"message": "Passwords must match."}
            )
                # generate user id
        id_list=[]
        while(True):
            user_id =utils.uid_gen()
            id_list = User.objects.filter(user_id=user_id)
            # if user id is unique then take it
            # otherwise generate user id again
            if(len(id_list)==0):
                break
        # Attempt to create new user, if user already exists ,raises integrity error
        try:
            # print(f"{name}\n {email}\n {contact}\n {alternate_contact}\n {password} and {confirmation}\n {dob}\n {gender}")
            user = User.objects.create_as_doc(
                firstname=firstname,
                lastname= lastname, 
                email=email,
                password=password,          
                primary_contact=contact,
                user_id=user_id,
                alternate_contact=alternate_contact,
                gender = gender,
                dob=dob,
                address=address,
                )
            user.save()
        except IntegrityError:
            return render(
                request,
                "as_doc/register.html",
                {"message": "Username already taken."},
            )
        login(request, user)
        return HttpResponseRedirect(reverse("as_doc:index"))
    else:
        return render(request, "as_doc/register.html")

@login_required(login_url="login")
def status(request):
    user = User.objects.get(user_id=request.user.user_id)
    if request.method=='GET':
        return render(request,
        "as_doc/status.html",{
            "doctor":user,

        })
    elif request.method=='POST':
        status = request.POST["status"]

        user.status = status
        user.save()
        
        return HttpResponseRedirect(reverse("as_doc:index"))

@login_required(login_url="login")
def edit_appointment(request,id):
    appointment = Appointment.objects.get(appointment_id=id)
    if request.method=="GET":
        return render(request,
        "as_doc/edit-appointment.html",{
            "appointment":appointment,
            "date":utils.date_to_string(appointment.date),
			"time":utils.time_to_str(appointment.time) +" "+ appointment.am_pm,
        })
    elif request.method == "POST":
        status = request.POST["status"]
        message =request.POST["message"]

        appointment.status = status
        appointment.message = message
        appointment.save()
        return HttpResponseRedirect(reverse("as_doc:index"))


@login_required(login_url="login")
def archive(request):
    user = User.objects.get(user_id=request.user.user_id)
    doctor_archive_appointments = user.assigned_patients.filter(status='D')
    return render(request,
    "as_doc/archive-appointment.html",{
            "doctor":user,
            "appointments":doctor_archive_appointments,
            "current_year":utils.get_year(),
    })

def edit_archive_appointment(request,id):
    appointment = Appointment.objects.get(appointment_id=id)
    if request.method == "GET":
        return render(request,
        "as_doc/edit-archive-appointment.html",{
            "appointment":appointment,
            "date":utils.date_to_string(appointment.date),
			"time":utils.time_to_str(appointment.time) +" "+ appointment.am_pm,
        })
    elif request.method == "POST":
        status = request.POST["status"]
        message =request.POST["message"]

        appointment.status = status
        appointment.message = message
        appointment.save()
        return HttpResponseRedirect(reverse("as_doc:archive"))

templates/as_doc/appointment.html
{% extends 'doctor_base_temp.html' %}
{% load static %}
{% load mathfilters %}

{% block customCSS %}
<style>
				.header {
				background: none;
				border-bottom: none;
				z-index: 1001;
				height: 60px;
				position: static;
				top: 0;
				right: 0;
				/* left: 18%; */
			}

			.sidebar {
				background-color: #fff;
				margin-top: 0;
				-webkit-transition: all 0.2s ease-in-out 0s;
				-ms-transition: all 0.2s ease-in-out 0s;
				transition: all 0.2s ease-in-out 0s;
				width: 240px;
				z-index: 1001;
				position: fixed;
				top: 0px;
				bottom: 0;
				left: 0;
			}

			.sidebar .sidebar-menu > ul > li > a {
				color: #000000;
			}

			.sidebar-menu ul li.active a {
				background-color: #1c3264;
				color: #fff;
			}

			.sidebar-menu > ul > li > a:hover {
				background-color: #1c3264 !important;
				color: #ffffff;
			}

			.user-header {
				background-color: #fff !important;
				display: flex;
				padding: 10px 15px;
				color: black;
			}

			.page-wrapper {
				margin-left: 240px;
				padding-top: 0px;
				position: relative;
				-webkit-transition: all 0.4s ease;
				-ms-transition: all 0.4s ease;
				transition: all 0.4s ease;
			}

			.btns{
				background-color: #1c3264 !important;
				border: 1px solid #1c3264;
			}

			.dash-widget-icon {
				display: inline-flex;
				font-size: 22px;
				height: 50px;
				line-height: 48px;
				text-align: center;
				width: 50px;
				border: none;
				border-radius: 0;
				padding: 28px;
			}

			.sidebar-menu ul li a {
                color: #000;
                display: block;
                font-size: 16px;
                height: auto;
                padding: 0 20px;
            }
			tr:hover{
				background-color: #dbdbdb;
				cursor: pointer;
			}
</style>
{% endblock %}

{% block doctor_name %}
{{doctor.firstname}} {{doctor.lastname}}
{% endblock %}
{% block doctor_email %}
{{doctor.email}}
<br>
{{doctor.user_id}}
{% endblock %}

{% block active %}
<li class="active"> 
	<a href="{% url 'as_doc:index' %}"><i class="fe fe-home"></i> <span>My Appointments</span></a>
</li>
<li> 
	<a href="{% url 'as_doc:archive' %}"><i class="fe fe-folder"></i> <span>Archive Appointments</span></a>
</li>
<li> 
	<a href="{% url 'as_doc:status' %}"><i class="fe fe-flag"></i> <span>My Status</span></a>
</li>
{% endblock %}



{% block content %}
			<!-- Page Wrapper -->
            <div class="page-wrapper">
			
                <div class="content container-fluid">
					<div class="col-sm-4 col-3">
						<h4 class="page-title">My Appointments</h4>
					</div>
					<div class="row">
						<div class="col-md-12">
						
							<!-- Recent Orders -->
							<div class="card card-table">
								<!-- <div class="card-header">
									<h4 class="card-title">My Cases</h4>
								</div> -->
								<div class="card-body">
									<div class="table-responsive">
										<table class="table table-center mb-0">
											<thead>
												<tr>
													<th>Appoinment ID</th>
                                                    <th>Patient Name</th>
													<th>Age</th>
													<th>Appoinment Date</th>
													<th>Appoinment Time</th>
													<th>Status</th>
												</tr>
											</thead>
											<tbody>
												{% for appointment in appointments %}
													<tr class='clickable-row' data-href='{% url "as_doc:edit_appointment" appointment.appointment_id  %}'>
														<td>APT-{{appointment.appointment_id}}</td>
														<td>{{appointment.patient.firstname}} {{appointment.patient.lastname}}</td>
														<td>{{current_year |sub:appointment.patient.dob.year}}</td>
														<td>{{appointment.date}}</td>
														<td>{{appointment.time}}</td>
														{% if appointment.status == 'C' %}
														<td><span class="custom-badge status-orange">🟡Confirmed</span></td>
														{% else %}
														<td><span class="custom-badge status-green">🟢 Active</span></td>
														{% endif %}
													</tr>
												
												{% empty %}
													<tr>
														<td>
															No Appointments found.
														</td>
													</tr>
												{% endfor %}
												
											</tbody>
										</table>
									</div>
								</div>
							</div>
							<!-- /Recent Orders -->
							
						</div>
					</div>
				</div>			
			</div>
			<!-- /Page Wrapper -->
{% endblock %}

templates/as_doc/archive-appointment.html
{% extends 'doctor_base_temp.html' %}
{% load static %}
{% load mathfilters %}

{% block customCSS %}
<style>
				.header {
				background: none;
				border-bottom: none;
				z-index: 1001;
				height: 60px;
				position: static;
				top: 0;
				right: 0;
				/* left: 18%; */
			}

			.sidebar {
				background-color: #fff;
				margin-top: 0;
				-webkit-transition: all 0.2s ease-in-out 0s;
				-ms-transition: all 0.2s ease-in-out 0s;
				transition: all 0.2s ease-in-out 0s;
				width: 240px;
				z-index: 1001;
				position: fixed;
				top: 0px;
				bottom: 0;
				left: 0;
			}

			.sidebar .sidebar-menu > ul > li > a {
				color: #000000;
			}

			.sidebar-menu ul li.active a {
				background-color: #1c3264;
				color: #fff;
			}

			.sidebar-menu > ul > li > a:hover {
				background-color: #1c3264 !important;
				color: #ffffff;
			}

			.user-header {
				background-color: #fff !important;
				display: flex;
				padding: 10px 15px;
				color: black;
			}

			.page-wrapper {
				margin-left: 240px;
				padding-top: 0px;
				position: relative;
				-webkit-transition: all 0.4s ease;
				-ms-transition: all 0.4s ease;
				transition: all 0.4s ease;
			}

			.btns{
				background-color: #1c3264 !important;
				border: 1px solid #1c3264;
			}

			.dash-widget-icon {
				display: inline-flex;
				font-size: 22px;
				height: 50px;
				line-height: 48px;
				text-align: center;
				width: 50px;
				border: none;
				border-radius: 0;
				padding: 28px;
			}

			.sidebar-menu ul li a {
                color: #000;
                display: block;
                font-size: 16px;
                height: auto;
                padding: 0 20px;
            }
			tr:hover{
				background-color: #dbdbdb;
				cursor: pointer;
			}
</style>
{% endblock %}

{% block doctor_name %}
{{doctor.firstname}} {{doctor.lastname}}
{% endblock %}
{% block doctor_email %}
{{doctor.email}}
<br>
{{doctor.user_id}}
{% endblock %}

{% block active %}
<li> 
	<a href="{% url 'as_doc:index' %}"><i class="fe fe-home"></i> <span>My Appointments</span></a>
</li>
<li class="active"> 
	<a href="{% url 'as_doc:archive' %}"><i class="fe fe-folder"></i> <span>Archive Appointments</span></a>
</li>
<li> 
	<a href="{% url 'as_doc:status' %}"><i class="fe fe-flag"></i> <span>My Status</span></a>
</li>
{% endblock %}



{% block content %}
			<!-- Page Wrapper -->
            <div class="page-wrapper">
			
                <div class="content container-fluid">
					<div class="col-sm-4 col-3">
						<h4 class="page-title">Archive Appointments</h4>
					</div>
					<div class="row">
						<div class="col-md-12">
						
							<!-- Recent Orders -->
							<div class="card card-table">
								<!-- <div class="card-header">
									<h4 class="card-title">My Cases</h4>
								</div> -->
								<div class="card-body">
									<div class="table-responsive">
										<table class="table table-center mb-0">
											<thead>
												<tr>
													<th>Appoinment ID</th>
                                                    <th>Patient Name</th>
													<th>Age</th>
													<th>Appoinment Date</th>
													<th>Appoinment Time</th>
													<th>Status</th>
												</tr>
											</thead>
											<tbody>
												{% for appointment in appointments %}
													<tr class='clickable-row' data-href='{% url "as_doc:edit_archive_appointment" appointment.appointment_id  %}'>
														<td>APT-{{appointment.appointment_id}}</td>
														<td>{{appointment.patient.firstname}} {{appointment.patient.lastname}}</td>
														<td>{{current_year |sub:appointment.patient.dob.year}}</td>
														<td>{{appointment.date}}</td>
														<td>{{appointment.time}}</td>
														{% if appointment.status == 'D' %}
														<td><span class="custom-badge status-orange">⚫Done</span></td>
														{% endif %}
													</tr>
												
												{% empty %}
													<tr>
														<td>
															No Appointments found.
														</td>
													</tr>
												{% endfor %}
												
											</tbody>
										</table>
									</div>
								</div>
							</div>
							<!-- /Recent Orders -->
							
						</div>
					</div>
				</div>			
			</div>
			<!-- /Page Wrapper -->
{% endblock %}

templates/as_doc/edit-appointment.html
{% extends 'doctor_base_temp.html' %}
{% load static %}
{% load mathfilters %}

{% block customCSS %}
<style>
				.header {
				background: none;
				border-bottom: none;
				z-index: 1001;
				height: 60px;
				position: static;
				top: 0;
				right: 0;
				/* left: 18%; */
			}

			.sidebar {
				background-color: #fff;
				margin-top: 0;
				-webkit-transition: all 0.2s ease-in-out 0s;
				-ms-transition: all 0.2s ease-in-out 0s;
				transition: all 0.2s ease-in-out 0s;
				width: 240px;
				z-index: 1001;
				position: fixed;
				top: 0px;
				bottom: 0;
				left: 0;
			}

			.sidebar .sidebar-menu > ul > li > a {
				color: #000000;
			}

			.sidebar-menu ul li.active a {
				background-color: #1c3264;
				color: #fff;
			}

			.sidebar-menu > ul > li > a:hover {
				background-color: #1c3264 !important;
				color: #ffffff;
			}

			.user-header {
				background-color: #fff !important;
				display: flex;
				padding: 10px 15px;
				color: black;
			}

			.page-wrapper {
				margin-left: 240px;
				padding-top: 0px;
				position: relative;
				-webkit-transition: all 0.4s ease;
				-ms-transition: all 0.4s ease;
				transition: all 0.4s ease;
			}

			.btns{
				background-color: #1c3264 !important;
				border: 1px solid #1c3264;
			}

			.dash-widget-icon {
				display: inline-flex;
				font-size: 22px;
				height: 50px;
				line-height: 48px;
				text-align: center;
				width: 50px;
				border: none;
				border-radius: 0;
				padding: 28px;
			}

			.sidebar-menu ul li a {
                color: #000;
                display: block;
                font-size: 16px;
                height: auto;
                padding: 0 20px;
            }
            .sidebar-menu li a:hover {
            color: #3a3a3a;
        }
    
    .btn-primary {
        border-color: transparent;
        background-color: #3a3a3a;
    }

    .btn-primary:hover {
        border: 1px solid #3a3a3a;
        background-color: #fff;
        color:#000;
    }

    .btn-primary:active:not(:disabled):not(.disabled)
    {
        border: 1px solid #3a3a3a;
        background-color: #fff;
        color:#000;
    }

    .page-item.active .page-link {
        background-color: #3a3a3a;
        border-color: #3a3a3a;
    }
</style>
{% endblock %}

{% block doctor_name %}
{{doctor.firstname}} {{doctor.lastname}}
{% endblock %}
{% block doctor_email %}
{{doctor.email}}
<br>
{{doctor.user_id}}
{% endblock %}

{% block active %}
<li class="active"> 
	<a href="{% url 'as_doc:index' %}"><i class="fe fe-home"></i> <span>My Appointments</span></a>
</li>
<li> 
	<a href="{% url 'as_doc:archive' %}"><i class="fe fe-folder"></i> <span>Archive Appointments</span></a>
</li>
<li> 
	<a href="{% url 'as_doc:status' %}"><i class="fe fe-flag"></i> <span>My Status</span></a>
</li>
{% endblock %}

{% block content  %}
<div class="page-wrapper">
            <div class="content">
                <div class="row">
                    <div class="col-sm-8  text-right m-b-20">
                        <h4 class="page-title">Edit Appointment</h4>
                    </div>
                    <div class="col-sm-4 text-center">
                        <a href="{% url 'as_doc:index' %}" class="btn btn-primary btn-rounded float-right">Back</a>
                         
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-8 offset-lg-2">
                        <form method="post" action="{% url 'as_doc:edit_appointment' appointment.appointment_id %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Appointment ID <span class="text-danger">*</span></label>
                                        <input class="form-control" type="text" name="appointment_id" value="APT-{{appointment.appointment_id}}" readonly>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Patient Name</label>
                                        <input class="form-control" type="text" name="patient_name" value="{{appointment.patient.firstname}} {{appointment.patient.lastname}}" readonly>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Doctor Name</label>
                                        <input class="form-control" type="text" name="doctor_name" value="{{appointment.doctor.firstname}} {{appointment.doctor.lastname}}" readonly>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Date</label>
                                        <div class="cal-icon">
                                            <input type="text" class="form-control datetimepicker" name="date" value="{{date}}" readonly>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Time</label>
                                        <div class="time-icon">
                                            <input type="text" class="form-control" id="datetimepicker3" name="time" value="{{time}}" readonly>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                                <div class="form-group">
                                <label>Message</label>
                                <textarea cols="40" rows="4" class="form-control" name="message" style="height: 200px;">{{appointment.message}}</textarea>
                            </div>
                            <div class="form-group">
                                <label class="display-block">Appointment Status</label>
                                <br>
                                <div class="form-check form-check-inline">
                                    {% if appointment.status == 'A' %}
                                    <input class="form-check-input" type="radio" name="status" id="product_active" value="A" checked>
                                    {% else %}
                                    <input class="form-check-input" type="radio" name="status" id="product_active" value="A">
                                    {% endif %}
                                    <label class="form-check-label" for="product_active">
                                    Active
                                    </label>
                                </div>
                                <div class="form-check form-check-inline">
                                    {% if appointment.status == 'C' %}
                                    <input class="form-check-input" type="radio" name="status" id="product_inactive" value="C" checked>
                                    {% else %}
                                    <input class="form-check-input" type="radio" name="status" id="product_inactive" value="C">
                                    {% endif %}
                                    <label class="form-check-label" for="product_inactive">
                                    Confirmed
                                    </label>
                                </div>
                                <div class="form-check form-check-inline">
                                    {% if appointment.status == 'D' %}
                                    <input class="form-check-input" type="radio" name="status" id="product_done" value="D" checked>
                                    {% else %}
                                    <input class="form-check-input" type="radio" name="status" id="product_done" value="D">
                                    {% endif %}
                                    <label class="form-check-label" for="product_done">
                                    Done
                                    </label>
                                </div>
                            </div>
                             
                            <div class="m-t-20 text-center">
                                <button name="add-appointment" class="btn btn-primary submit-btn">Save Appointment</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
		</div>
{% endblock %}

templates/as_doc/index.html
<!-- this is Assistant Doctor dashboard -->
<html>
    <head>
        <title>Dashboard</title>
    </head>
    <body>
        <h1>{{user.name}}</h1>
        <h1>This is Assistant Doctor</h1>

        <a href="{% url 'as_doc:logout' %}">logout</a>
    </body>
</html>

templates/as_doc/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>Customer - Login</title>
		
		<!-- Favicon -->
        <!-- <link rel="shortcut icon" type="image/x-icon" href="../../static/assets/img/logo.jpeg"> -->

		<!-- Bootstrap CSS -->
        <!-- <link rel="stylesheet" href="../../static/assets/css/bootstrap.min.css">    -->
		<link rel="stylesheet" href="{% static '/assets/css/bootstrap.min.css' %}"> 
		
		<!-- Fontawesome CSS -->
        <link rel="stylesheet" href="{% static '/assets/css/font-awesome.min.css' %}">
		
		<!-- Main CSS -->

        <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">

		<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

		<style>
			.toggle-password{
				font-size: 16px;
				position: absolute;
				top: 51%;
				right: 23%;
				transform: translateY(-50%);
				-webkit-transform: translateY(-50%);
				-ms-transform: translateY(-50%);
				color: #797979;
				cursor: pointer;
				width: 32px;
				height: 32px;
				border-radius: 50%;
			}
		</style>
        
    </head>
    <body>
	
		<!-- Main Wrapper -->
        <div class="main-wrapper login-body">
            <div class="login-wrapper">
            	<div class="container">
                	<div class="loginbox">
                    	<div class="login-left">
							<img class="img-fluid" src="{% static 'assets/img/logo.jpeg' %}" alt="Logo">
                        </div>
                        <div class="login-right">
							<div class="login-right-wrap">
								<h1>Doctor Login</h1>
								<p class="account-subtitle">Access to our dashboard</p>
								<p>
									{% if message %}
										<p>{{message}}</p>
									{% endif %}
								</p>
								<!-- Form -->
								<form action="{% url 'as_doc:login' %}" method="post">
									{% csrf_token %}
									<div class="form-group">
										<input class="form-control" type="text" placeholder="Email" 
										name="email"
										required>
									</div>
									<div class="form-group">
										<div class="pass-group">
											<input class="form-control pass-input" type="password" placeholder="Password" 
											name="password"
											required>
											<!-- <span class="feather-eye toggle-password"></span> -->
											<i class="fa fa-eye feather-eye toggle-password " aria-hidden="true"></i>
										</div>
									</div>
									<div class="form-group">
										<button class="btn btn-primary w-100 " type="submit">Login</button>
									</div>
								</form>
								<!-- /Form -->
								
								<div class="text-center forgotpass"><a href="{% url 'patient:forgotpswd' %}">Forgot Password?</a></div>
																
								<div class="text-center dont-have">Don’t have an account? <a href="{% url 'as_doc:register' %}">Register</a></div>
							</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
		<!-- /Main Wrapper -->
		
		<!-- jQuery -->
        <script src="{% static 'assets/js/jquery-3.6.4.min.js' %}"></script>
		
		<!-- Bootstrap Core JS -->
        <script src="{% static  'assets/js/bootstrap.bundle.min.js' %}"></script>
		
		<!-- Custom JS -->
		<script src="{% static 'assets/js/script.js' %}"></script>
		<script>
				if ($('.toggle-password').length > 0) {
				$(document).on('click', '.toggle-password', function () {
					$(this).toggleClass("feather-eye-off");
					var input = $(".pass-input");
					if (input.attr("type") == "password") {
						input.attr("type", "text");
					} else {
						input.attr("type", "password");
					}
				});
			}
		</script>
		
    </body>
</html>