as_doc/urls.py
from django.urls import path
from . import views

app_name = 'as_doc'
urlpatterns=[
    path("",views.index,name="index"),
    path("login/",views.as_doclogin,name="login"),
    path("register/",views.as_docregister,name="register"),
    path("logout/",views.as_doclogout,name="logout"),
    path("status/",views.status,name="status"),
    path("<str:id>/edit_appointment",views.edit_appointment,name="edit_appointment"),
    path("archive/",views.archive,name="archive"),
    path("<str:id>/edit_archive_appointment",views.edit_archive_appointment,name="edit_archive_appointment"),
]

patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'
urlpatterns=[
    path("",views.index,name="index"),
    path("plogin/",views.patient_login,name="plogin"),
    path("plogout/",views.patient_logout,name="plogout"),
    path("pregister/",views.patient_register,name="pregister"),
    path("forgot-password/",views.forgot_pswd,name="forgotpswd"),
    path("<str:userid>/diseases",views.associateOfDiseases,name="associateOfDiseases"),
]

projectH/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patients/',include("patient.urls")),
    path('assistdoc/',include("as_doc.urls")),
    path('admindoc/',include("admin_doc.urls")),
    path('reception/',include("reception.urls")),
]

reception/urls.py
from django.urls import path
from . import views

app_name = 'reception'
urlpatterns=[

    path("",views.index,name='index'),
    path("login/",views.reception_login,name="login"),
    path("logout/",views.reception_logout,name="logout"),
#   doctors
    path("doctors/",views.show_doctors,name="show_doctors"),
    path("add-doctor/",views.add_doctor,name="add_doctor"),
    path("<str:id>/edit-doctor/",views.edit_doctor,name="edit_doctor"),
    path("<str:id>/delete-doctor/",views.delete_doctor,name="delete_doctor"),
    path("<str:id>/update-doctor-password/",views.update_doctor_password,name="update_doctor_password"),
#   patients
    path("patients/",views.show_patients,name="show_patients"),
    path("add-patient/",views.add_patient,name="add_patient"),
    path("<str:id>/edit-patient/",views.edit_patient,name="edit_patient"),
    path("<str:id>/delete-patient/",views.delete_patient,name="delete_patient"),
    path("<str:id>/update-patient-password/",views.update_patient_password,name="update_patient_password"),

    # appointments
    path("appointments/",views.show_appointments,name="show_appointments"),
    path("add-appointment/",views.add_appointment,name="add_appointment"),
    path("<str:appointment_id>/edit-appointment/",views.edit_appointment,name="edit_appointment"),
    path("<str:appointment_id>/delete-appointment/",views.delete_appointment,name="delete_appointment"),

    # archives
    path("archive-appointment/",views.show_archive_appointments,name="show_archive_appointments"),
    path("<str:appointment_id>/archive_appointment/",views.archive_appointment,name="archive_appointment"),
    path("<str:appointment_id>/unarchive_appointment/",views.unarchive_appointment,name="unarchive_appointment"),
    path("<str:appointment_id>/edit_unarchive_appointment/",views.edit_archive_appointment,name="edit_archive_appointment"),


    # Doctor Schedule
    path("schedules/",views.show_doctor_schedules,name="show_doctor_schedules"),
    path("add-schedule/",views.add_doctor_schedule,name="add_doctor_schedule"),
    path("<int:id>/edit-schedule/",views.edit_doctor_schedule,name="edit_doctor_schedule"),
    path("<int:id>/delete-schedule/",views.delete_doctor_schedule,name="delete_doctor_schedule"),


    
]

templates/customer_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>Customer - Dashboard</title>
		<!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{% static '/assets/img/favicon.png' %}">
		
		<!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
		
		<!-- Fontawesome CSS -->
        <link rel="stylesheet" href="{% static '/assets/css/font-awesome.min.css' %}">
		
		<!-- Feathericon CSS -->
        <link rel="stylesheet" href="{% static '/assets/css/feathericon.min.css' %}">
		
		<link rel="stylesheet" href="{% static '/assets/plugins/morris/morris.css' %}">
		
		<!-- Main CSS -->
        <link rel="stylesheet" href="{% static '/assets/css/custom.css' %}">

		<style>
			.header {
				background: none;
				border-bottom: none;
				z-index: 1001;
				height: 60px;
				position: static;
				top: 0;
				right: 0;
				/* left: 18%; */
			}

			.sidebar {
				background-color: #fff;
				margin-top: 0;
				-webkit-transition: all 0.2s ease-in-out 0s;
				-ms-transition: all 0.2s ease-in-out 0s;
				transition: all 0.2s ease-in-out 0s;
				width: 240px;
				z-index: 1001;
				position: fixed;
				top: 0px;
				bottom: 0;
				left: 0;
			}

			.sidebar .sidebar-menu > ul > li > a {
				color: #000000;
			}

			.sidebar-menu ul li.active a {
				background-color: #1c3264;
				color: #fff;
			}

			.sidebar-menu > ul > li > a:hover {
				background-color: #1c3264 !important;
				color: #ffffff;
			}

			.user-header {
				background-color: #fff !important;
				display: flex;
				padding: 10px 15px;
				color: black;
			}

			.page-wrapper {
				margin-left: 240px;
				padding-top: 0px;
				position: relative;
				-webkit-transition: all 0.4s ease;
				-ms-transition: all 0.4s ease;
				transition: all 0.4s ease;
			}

			
		</style>
        
    </head>
    <body>
	
		<!-- Main Wrapper -->
        <div class="main-wrapper">
		
			<div class="header">
				
				<div class="header-left"></div>
				<a href="javascript:void(0);" id="toggle_btn">
					<i class="fe fe-text-align-left"></i>
				</a>
				
				<!-- Mobile Menu Toggle -->
				<a class="mobile_btn" id="mobile_btn">
					<i class="fa fa-bars"></i>
				</a>
				<!-- /Mobile Menu Toggle -->				
			</div>
			<!-- /Header -->
		
			
			
			<!-- Sidebar -->
            <div class="sidebar" id="sidebar">
					
                <div class="sidebar-inner ">
					<div id="sidebar-menu" class="sidebar-menu">
						<ul>
							<li class="menu-title"> 
								<!-- Logo -->
								<div class="m-auto">
									<a href="customer-dashboard.html" class="logo">
										<img src="../../static/assets/img/logo.jpeg" alt="Logo">
									</a>
								</div>
								<!-- /Logo -->
								
							</li>
							<hr>
							<li class="menu-title">
								<div class="user-header">
									<div class="avatar avatar-sm">
										<i class="fe fe-user" style="font-size: 35px"></i>
										<!-- <img src="assets/img/profiles/avatar-01.jpg" alt="User Image" class="avatar-img rounded-circle"> -->
									</div>
									<div class="user-text">
										<h6>Name</h6>
										<p class="text-muted mb-0">name@gmail.com</p>
									</div>
								</div>
							</li>
							<li class="active"> 
								<a href="customer-dashboard.html"><i class="fe fe-home"></i> <span>Dashboard</span></a>
							</li>
							<li> 
								<a href="profile-setting.html"><i class="fe fe-user-plus"></i> <span>Profile</span></a>
							</li>
							<li> 
								<a href="appointment-list.html"><i class="fe fe-layout"></i> <span>My Case</span></a>
							</li>
							<li> 
								<a href="{% url 'patient:associateOfDiseases' user.user_id %}"><i class="fe fe-layout"></i> <span>Associate of Diseases</span></a>
							</li>
							<li>
								<a href="{% url 'patient:plogout' %}"><i class="fe fe-logout"></i> <span>Logout</span></a>
							</li>
						</ul>
					</div>
                </div>
            </div>
			<!-- /Sidebar -->

			
			{% block content %}
			{% endblock  %}
		
        </div>
		<!-- /Main Wrapper -->
		
		
		<!-- jQuery -->
        <script src="{% static 'assets/js/jquery-3.6.4.min.js' %}"></script>
		
		<!-- Bootstrap Core JS -->
        <script src="{% static '/assets/js/bootstrap.bundle.min.js' %}"></script>
		
		<!-- Slimscroll JS -->
        <script src="{% static '/assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
		
		<script src="{% static '/assets/plugins/raphael/raphael.min.js' %}"></script>    
		<script src="{% static '/assets/plugins/morris/morris.min.js' %}"></script>  
		<script src="../../static/assets/js/chart.morris.js' %}"></script>
		
		<!-- Custom JS -->
		<script  src="{% static '/assets/js/script.js' %}"></script>
		
    </body>
</html>

<!-- resolved, nt resolved -->

templates/doctor_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>Customer - Dashboard</title>

        
		<!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{% static '/assets/img/favicon.png' %}">
		
		<!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static '/assets/css/bootstrap.min.css' %}">
		
		<!-- Fontawesome CSS -->
        <link rel="stylesheet" href="{% static '/assets/css/font-awesome.min.css' %}">
		
		<!-- Feathericon CSS -->
        <link rel="stylesheet" href="{% static '/assets/css/feathericon.min.css' %}">
		
		<link rel="stylesheet" href="{% static '/assets/plugins/morris/morris.css' %}">
		
		<!-- Main CSS -->
        <link rel="stylesheet" href="{% static '/assets/css/custom.css' %}">

		{% block customCSS %}
		{% endblock %}
        
    </head>
    <body>
	
		<!-- Main Wrapper -->
        <div class="main-wrapper">
		
			<div class="header">
				
				<div class="header-left"></div>
				<a href="javascript:void(0);" id="toggle_btn">
					<i class="fe fe-text-align-left"></i>
				</a>
				
				<!-- Mobile Menu Toggle -->
				<a class="mobile_btn" id="mobile_btn">
					<i class="fa fa-bars"></i>
				</a>
				<!-- /Mobile Menu Toggle -->				
			</div>
			<!-- /Header -->
		
			
			<!-- Sidebar -->
            <div class="sidebar" id="sidebar">
					
                <div class="sidebar-inner ">
					<div id="sidebar-menu" class="sidebar-menu">
						<ul>
							<li class="menu-title"> 
								<!-- Logo -->
								<div class="m-auto">
									<a href="index.html" class="logo">
										<img src="../assets/img/logo.jpeg" alt="Logo">
									</a>
								</div>
								<!-- /Logo -->
								
							</li>
							<hr>
							<li class="menu-title">
								<div class="user-header">
									<div class="avatar avatar-sm">
										<i class="fe fe-user" style="font-size: 35px"></i>
										<!-- <img src="assets/img/profiles/avatar-01.jpg" alt="User Image" class="avatar-img rounded-circle"> -->
									</div>
									<div class="user-text">
										<h6>Name</h6>
										<p class="text-muted mb-0">name@gmail.com</p>
									</div>
								</div>
							</li>
							<li class="active"> 
								<a href="doctor-dashboard.html"><i class="fe fe-home"></i> <span>Dashboard</span></a>
							</li>
							<li> 
								<a href="profile-setting.html"><i class="fe fe-user-plus"></i> <span>Profile</span></a>
							</li>
							<li> 
								<a href="my-patients.html"><i class="fe fe-user-plus"></i> <span>My Patients</span></a>
							</li>
							<li class="submenu">
								<a href="#"><i class="fe fe-document"></i> <span> Kingdoms</span> <span class="menu-arrow"></span></a>
								<ul style="display: none;">
									<li><a href="kingdom1.html">Animal</a></li>
									<li><a href="kingdom2.html">Plant</a></li>
									<li><a href="kingdom3.html">Minerals</a></li>
									<li><a href="chart.html">Chart</a></li>
									<li><a href="DonutChart.html">Doughnut Chart</a></li>
									<li><a href="chart1.html">Histogram</a></li>
								</ul>
							</li>
							<li> 
								<a href="appointment-list.html"><i class="fe fe-layout"></i> <span>My Case</span></a>
							</li>
							<li>
								<a href="#"><i class="fe fe-logout"></i> <span>Logout</span></a>
							</li>
						</ul>
					</div>
                </div>
            </div>
			<!-- /Sidebar -->

			{% block content %}
			{% endblock %}
					
        </div>
		<!-- /Main Wrapper -->
		
		<!-- jQuery -->
        <script src="{% static '/assets/js/jquery-3.6.4.min.js' %}"></script>
		
		<!-- Bootstrap Core JS -->
        <script src="{% static '/assets/js/bootstrap.bundle.min.js' %}"></script>
		
		<!-- Slimscroll JS -->
        <script src="{% static '/assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
		
		<script src="{% static '/assets/plugins/raphael/raphael.min.js' %}"></script>    
		<script src="{% static '/assets/plugins/morris/morris.min.js' %}"></script>  
		<script src="{% static '/assets/js/chart.morris.js' %}"></script>
		
		<!-- Custom JS -->
		<script  src="{% static '/assets/js/script.js' %}"></script>
		
    </body>
</html>

templates/doctor_base_temp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>My Appointments</title>

        
		<!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{% static '/assets/img/favicon.png' %}">
		
		<!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static '/assets/css/bootstrap.min.css' %}">
		
		<!-- Fontawesome CSS -->
        <link rel="stylesheet" href="{% static '/assets/css/font-awesome.min.css' %}">
		
		<!-- Feathericon CSS -->
        <link rel="stylesheet" href="{% static '/assets/css/feathericon.min.css' %}">
		
		<link rel="stylesheet" href="{% static '/assets/plugins/morris/morris.css' %}">
		
		<!-- Main CSS -->
        <link rel="stylesheet" href="{% static '/assets/css/custom.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'assets/css/loader.css' %}">
        <script src="{% static 'assets/js/loader.js' %}"></script>

		{% block customCSS %}
		{% endblock %}
        
    </head>
	<div id="overlay">
		<div id="progstat"></div>
		<div id="progress"></div>
	</div>
	<div>
	<!-- <div class="flex-center flex-column mt-5 mb-5">
	  <h1 class="animated fadeIn mb-2">This is a simple page loader</h1>
	   <h5 class="animated fadeIn mb-1">Using no extra plugins, we use the power of javascript & basic css to create a seamless page loader.</h5>
	
	  <p class="animated fadeIn text-muted">Whitney S Rogers creation - GR FREEDOM DEV</p>
	   -->
	
	  <!-- <div id="container" class="mt-5 text-center">
		<h4 class="mb-5">Let's load some heavy images to test page loader!</h4>
		<div class="container">
		  <div class="row mb-5">
			<div class="col"><img src="http://placehold.it/3000x3000/cf5" class="img-fluid"></div>
			<div class="col"><img src="http://placehold.it/3000x3000/cf1" class="img-fluid"></div>
		  </div> -->
		  <div class="row"> 
			<!-- <div class="col"><img src="http://placehold.it/3000x3000/cf2" class="img-fluid"></div> -->
			<div class="col"><img src="http://placehold.it/3000x3000/cf3" class="img-fluid"></div>
		  </div>
		</div> 
	  </div> 
	</div>
	</div>
	<!-- /Start your project here-->
	<!-- loader code end -->
    <body>
	
	
		<!-- Main Wrapper -->
        <div class="main-wrapper">
		
			<div class="header">
				
				<div class="header-left"></div>
				<a href="javascript:void(0);" id="toggle_btn">
					<i class="fe fe-text-align-left"></i>
				</a>
				
				<!-- Mobile Menu Toggle -->
				<a class="mobile_btn" id="mobile_btn">
					<i class="fa fa-bars"></i>
				</a>
				<!-- /Mobile Menu Toggle -->				
			</div>
			<!-- /Header -->
		
			
			<!-- Sidebar -->
            <div class="sidebar" id="sidebar">
					
                <div class="sidebar-inner ">
					<div id="sidebar-menu" class="sidebar-menu">
						<ul>
							<li class="menu-title">
								<div class="user-header">
									<div class="avatar avatar-sm">
										<!-- <i class="fe fe-user" style="font-size: 35px"></i> -->
										<i class="fa fa-user-md" style="font-size: 35px"></i>
										<!-- <img src="assets/img/profiles/avatar-01.jpg" alt="User Image" class="avatar-img rounded-circle"> -->
									</div>
									<div class="user-text">
										<h6>
										{% block doctor_name %}
										Name
										{% endblock %}
										</h6>

										<p class="text-muted mb-0">
											{% block doctor_email %}
											name@gmail.com
											{% endblock %}
										</p>
									</div>
								</div>
							</li>
							{% block active %}
							<li class="active"> 
								<a href="{% url 'as_doc:index' %}"><i class="fe fe-home"></i> <span>My Appointments</span></a>
							</li>
							<li> 
								<a href="{% url 'as_doc:archive' %}"><i class="fe fe-box-archive"></i> <span>Archive Appointments</span></a>
							</li>
							<li> 
								<a href="{% url 'as_doc:status' %}"><i class="fe fe-flag"></i> <span>My Status</span></a>
							</li>
							{% endblock %}
							<li>
								<a href="{% url 'as_doc:logout' %}"><i class="fe fe-logout"></i> <span>Logout</span></a>
							</li>
						</ul>
					</div>
                </div>
            </div>
			<!-- /Sidebar -->

			{% block content %}
			{% endblock %}
					
        </div>
		<!-- /Main Wrapper -->
		
		<!-- jQuery -->
        <script src="{% static '/assets/js/jquery-3.6.4.min.js' %}"></script>
		
		<!-- Bootstrap Core JS -->
        <script src="{% static '/assets/js/bootstrap.bundle.min.js' %}"></script>
		
		<!-- Slimscroll JS -->
        <script src="{% static '/assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
		
		<script src="{% static '/assets/plugins/raphael/raphael.min.js' %}"></script>    
		<script src="{% static '/assets/plugins/morris/morris.min.js' %}"></script>  
		<script src="{% static '/assets/js/chart.morris.js' %}"></script>
		
		<!-- Custom JS -->
		<script  src="{% static '/assets/js/script.js' %}"></script>
		
    </body>
</html>

templates/reception footer.html
{% load static %}
<div class="sidebar-overlay" data-reff=""></div>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" ></script>
    <!-- <script src="assets/js/jquery-3.2.1.min.js"></script> -->
	<script src="{% static 'assets/js/receptionpopper.min.js' %}"></script>
    <script src="{% static 'assets/js/receptionbootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/receptionjquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/js/receptiondataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'assets/js/receptionjquery.slimscroll.js' %}"></script>
    <script src="{% static 'assets/js/receptionChart.bundle.js' %}"></script>
    <script src="{% static 'assets/js/receptionchart.js' %}"></script>
    <script src="{% static 'assets/js/receptionapp.js' %}"></script>
    <script src="{% static 'assets/js/receptionselect2.min.js' %}"></script>
    <script src="{% static 'assets/js/receptionmoment.min.js' %}"></script>
    <script src="{% static 'assets/js/receptionbootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap-select.min.js' %}"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    {% block addonJS %}
    {% endblock %}
    

<script>
            $(function () {
                $('#datetimepicker3').datetimepicker({
                    format: 'LT'

                });
                $('#datetimepicker4').datetimepicker({
                    format: 'LT'
                });
            });
     </script>

</body>
</html>

templates/reception header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="">
    <title>HMS</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/receptionbootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/receptionselect2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/receptionbootstrap-datetimepicker.min.css' %}">
    <link href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/receptionstyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/loader.css' %}">
    <script src="{% static 'assets/js/loader.js' %}"></script>
<style>
        .header {
            background-color: #3a3a3a;
            left: 0;
            position: fixed;
            right: 0;
            top: 0;
            z-index: 1039;
            height: 50px;
            box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
        }

        .sidebar-menu li a:hover {
            color: #3a3a3a;
        }
    
    .btn-primary {
        border-color: transparent;
        background-color: #3a3a3a;
    }

    .btn-primary:hover {
        border: 1px solid #3a3a3a;
        background-color: #fff;
        color:#000;
    }

    .btn-primary:active:not(:disabled):not(.disabled)
    {
        border: 1px solid #3a3a3a;
        background-color: #fff;
        color:#000;
    }

    .page-item.active .page-link {
        background-color: #3a3a3a;
        border-color: #3a3a3a;
    }
</style>
    
</head>
<!-- loader code start -->
<div id="overlay">
    <div id="progstat"></div>
    <div id="progress"></div>
</div>
<div>
<!-- <div class="flex-center flex-column mt-5 mb-5">
  <h1 class="animated fadeIn mb-2">This is a simple page loader</h1>
   <h5 class="animated fadeIn mb-1">Using no extra plugins, we use the power of javascript & basic css to create a seamless page loader.</h5>

  <p class="animated fadeIn text-muted">Whitney S Rogers creation - GR FREEDOM DEV</p>
   -->

  <!-- <div id="container" class="mt-5 text-center">
    <h4 class="mb-5">Let's load some heavy images to test page loader!</h4>
    <div class="container">
      <div class="row mb-5">
        <div class="col"><img src="http://placehold.it/3000x3000/cf5" class="img-fluid"></div>
        <div class="col"><img src="http://placehold.it/3000x3000/cf1" class="img-fluid"></div>
      </div>
      <div class="row">
        <div class="col"><img src="http://placehold.it/3000x3000/cf2" class="img-fluid"></div>
        <div class="col"><img src="http://placehold.it/3000x3000/cf3" class="img-fluid"></div>
      </div>
    </div> -->
  </div> 
</div>
</div>
<!-- /Start your project here-->
<!-- loader code end -->

<body>
    <div class="main-wrapper">
        <div class="header">
			<div class="header-left">
				<a href="{% url 'reception:index' %}" class="logo">
					<!-- <img src="#" width="35" height="35" alt=""> <span>HMS</span> -->
				</a>
			</div>
			<a id="toggle_btn" href="javascript:void(0);"><i class="fa fa-bars"></i></a>
            <a id="mobile_btn" class="mobile_btn float-left" href="#sidebar"><i class="fa fa-bars"></i></a>
            <ul class="nav user-menu float-right">
                   <li class="nav-item dropdown has-arrow">
                    <a href="#" class="dropdown-toggle nav-link user-link" data-toggle="dropdown">
                        <span class="user-img">
							<img class="rounded-circle" src="{% static 'assets/img/receptionuser.jpg' %}" width="24" alt="Admin">
							<span class="status online"></span>
						</span>
                        {{user.firstname}}
                    </a>
					<div class="dropdown-menu">
						<a class="dropdown-item" href="{% url 'reception:logout' %}">Logout</a>
					</div>
                </li>
            </ul>
            <div class="dropdown mobile-user-menu float-right">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="{% url 'reception:logout' %}">Logout</a>
                </div>
            </div>
        </div>

        <div class="sidebar" id="sidebar">
            <div class="sidebar-inner slimscroll">
                <div id="sidebar-menu" class="sidebar-menu">
                    <ul>
                        {% block dashboard %}
                        <li class="active">
                            <a href="{% url 'reception:index' %}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a>
                        </li>
                        {% endblock %}

                        {% block doctors %}
						<li>
                            <a href="{% url 'reception:show_doctors' %}"><i class="fa fa-user-md"></i> <span>Doctors</span></a>
                        </li>
                        {% endblock %}

                        {% block patients %}
                        <li>
                            <a href="{% url 'reception:show_patients' %}"><i class="fa fa-wheelchair"></i> <span>Patients</span></a>
                        </li>
                        {% endblock %}

                        {% block appointments %}
                        <li>
                            <a href="{% url 'reception:show_appointments' %}"><i class="fa fa-calendar"></i> <span>Appointments</span></a>
                        </li>
                        {% endblock %}
                        {% block archiveappointments %}
                        <li>
                            <a href="{% url 'reception:show_archive_appointments' %}"><i class="fa fa-calendar"></i> <span>Archive Appointments</span></a>
                        </li>
                        {% endblock %}

                        {% block doctor_schedule %}
                        <li>
                            <a href="{% url 'reception:show_doctor_schedules' %}"><i class="fa fa-calendar-check-o"></i> <span>Doctor Schedule</span></a>
                        </li>
                        {% endblock %}		                       
                    </ul>
                </div>
            </div>
      </div>
</div>

templates/reception_base.html
{% include 'reception header.html' %}
{% block content %}
{% endblock %}
{% include 'reception footer.html' %}